spring:
    application:
        name: user-service
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/user-service
        username: userservice
        password: userservice
        
    jpa:
        hibernate:
           ddl-auto: update
           dialect: org.hibernate.dialect.MySQLDialect
           show-sql: false
security:
    user:
       password: password
           
server:
    port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/